version: '3.8'

services:
  db:
    image: postgres:16
    container_name: company-db
    environment:
      POSTGRES_DB: companyscreener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"