-- ============================================================
-- V2__seed_companies.sql
-- Seeds 30 companies. ON CONFLICT DO NOTHING makes this
-- idempotent — safe to re-run without duplicate errors.
-- ============================================================

INSERT INTO companies (name, sector, country, description, founded_year, employee_count)
VALUES
    ('Stripe',      'FinTech',                  'USA',         'Stripe is a financial infrastructure platform for businesses of every size. It processes hundreds of billions of dollars annually for millions of companies worldwide.',                                                          2010, 8000),
    ('Spotify',     'Media & Entertainment',    'Sweden',      'Global audio streaming platform offering music, podcasts, and audiobooks with over 600 million active users across 180+ markets.',                                                                                               2006, 9800),
    ('Tesla',       'Automotive & Energy',      'USA',         'American multinational company designing and manufacturing electric vehicles, battery energy storage systems, and solar energy products.',                                                                                        2003, 127855),
    ('Airbnb',      'Travel & Hospitality',     'USA',         'Online marketplace connecting hosts with guests for short-term lodging and unique travel experiences across 220+ countries and regions.',                                                                                         2008, 6907),
    ('Shopify',     'E-Commerce',               'Canada',      'E-commerce platform powering over 1.7 million businesses worldwide with tools for payments, shipping, marketing, and storefront management.',                                                                                     2006, 11600),
    ('OpenAI',      'Artificial Intelligence',  'USA',         'AI safety company and research laboratory behind GPT-4, DALL-E, and ChatGPT. Mission is to ensure artificial general intelligence benefits all of humanity.',                                                                     2015, 1500),
    ('Klarna',      'FinTech',                  'Sweden',      'Swedish buy-now-pay-later fintech platform serving over 150 million consumers and 450,000 retail partners globally.',                                                                                                            2005, 5000),
    ('Canva',       'Design & SaaS',            'Australia',   'Online graphic design platform with 170 million users offering drag-and-drop tools, templates, and a vast asset library for visual content creation.',                                                                           2013, 3500),
    ('Google',      'Technology',               'USA',         'Multinational technology company specializing in internet-related services including search, cloud computing, advertising, and consumer hardware. A subsidiary of Alphabet Inc.',                                                 1998, 180000),
    ('Microsoft',   'Technology',               'USA',         'Global technology corporation offering software, cloud services (Azure), gaming (Xbox), and enterprise solutions. Creator of Windows and Office suite.',                                                                          1975, 221000),
    ('Apple',       'Technology',               'USA',         'Consumer electronics and software company known for iPhone, Mac, iPad, and a tightly integrated ecosystem of hardware and services.',                                                                                            1976, 164000),
    ('Amazon',      'E-Commerce & Cloud',       'USA',         'Global leader in e-commerce and cloud computing through AWS. Also operates digital streaming, AI assistants, and logistics infrastructure.',                                                                                     1994, 152500),
    ('Meta',        'Social Media',             'USA',         'Technology conglomerate owning Facebook, Instagram, WhatsApp, and Threads. Focused on social networking and the development of the metaverse.',                                                                                  2004, 70000),
    ('PayPal',      'FinTech',                  'USA',         'Digital payments platform enabling online money transfers and payments for consumers and businesses in 200+ markets.',                                                                                                           1998, 29000),
    ('Revolut',     'FinTech',                  'UK',          'Digital banking and financial super-app offering currency exchange, stock trading, crypto, and banking services to 45+ million customers.',                                                                                      2015, 8000),
    ('Salesforce',  'CRM & SaaS',               'USA',         'World''s leading CRM platform providing sales, service, marketing, and analytics cloud solutions for businesses of all sizes.',                                                                                                  1999, 80000),
    ('Notion',      'Productivity',             'USA',         'All-in-one workspace combining notes, wikis, databases, and project management used by millions of individuals and teams globally.',                                                                                              2016, 600),
    ('Atlassian',   'Software',                 'Australia',   'Developer tools company behind Jira, Confluence, and Trello. Serves over 300,000 organizations worldwide.',                                                                                                                     2002, 13000),
    ('Nvidia',      'Semiconductors',           'USA',         'Designer of GPUs and AI computing platforms. Dominant supplier for AI training infrastructure and a key enabler of the generative AI revolution.',                                                                               1993, 29600),
    ('Palantir',    'Data Analytics',           'USA',         'Data analytics and AI platform company serving government agencies and commercial enterprises with software for complex data integration and analysis.',                                                                           2003, 3800),
    ('Databricks',  'AI & Data',                'USA',         'Unified data analytics and AI platform built on Apache Spark. Enables data engineering, ML, and business intelligence at scale.',                                                                                                2013, 7000),
    ('SAP',         'Enterprise Software',      'Germany',     'World''s largest enterprise application software company, offering ERP, supply chain, finance, and HR solutions to 400,000+ customers.',                                                                                        1972, 110000),
    ('Figma',       'Design Software',          'USA',         'Collaborative interface design tool used by product teams for UI/UX design, prototyping, and design systems management.',                                                                                                        2012, 1000),
    ('Discord',     'Communication',            'USA',         'Voice, video, and text communication platform originally built for gamers, now serving 200 million active users across diverse communities.',                                                                                     2015, 7000),
    ('GitHub',      'Developer Tools',          'USA',         'Code hosting and collaboration platform with 100 million developers. Provides version control, CI/CD, and open-source community tools. Acquired by Microsoft in 2018.',                                                          2008, 4000),
    ('LinkedIn',    'Professional Network',     'USA',         'Professional social networking platform with 1 billion members used for job searching, recruiting, and B2B marketing. Owned by Microsoft.',                                                                                      2003, 20000),
    ('Uber',        'Mobility',                 'USA',         'Global ride-hailing and delivery platform operating in 70+ countries with services including ridesharing, Uber Eats food delivery, and freight.',                                                                                 2009, 32000),
    ('Bolt',        'Mobility',                 'Estonia',     'European and African ride-hailing and delivery platform operating in 45+ countries with 100 million customers.',                                                                                                                  2013, 4000),
    ('Booking.com', 'Travel',                   'Netherlands', 'World''s leading online travel platform offering accommodation, flights, car rentals, and attractions with 28+ million listings.',                                                                                               1996, 22000),
    ('Snowflake',   'Cloud & Data',             'USA',         'Cloud data platform offering data warehousing, data sharing, and analytics-as-a-service across multiple cloud providers.',                                                                                                       2012, 6800)
ON CONFLICT (name) DO NOTHING;
